[project]
name = "audiobreaker-v01"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "gtts>=2.5.4",
    "just-playback>=0.1.8",
]
