[project]
name = "gpttest"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "just-playback>=0.1.8",
    "openai[voice-helpers]>=1.76.0",
]
